```{r}
library(lubridate)
library(dplyr)
```
```{r}
# Reading data: 

data_original = read.csv("congo_original_mod.csv", sep = ",", header = TRUE)

original_coordinates = read.csv("C:/Users/Larissa/Downloads/Larissa_Final_Thesis_Data/Larissa_Final_Thesis_Data/Citizen science data (raw and processed)/FOR_CONGO_UGANDA_DRIVE/Complete_Validation/Congo_snails_variables/Watercontact_sites_lukungacorrect.csv", sep = ",", header = TRUE)

# 1. Filter reports of citizens no sampling (Reading GPS location as an indication) 

data_1 <- data_original %>%
    filter(!is.na(X_Take.a.GPS.point_latitude))
```
```{r}
# 2. Dates (outside the range) 

data_2 <- data_1 %>%
  filter(!(today < '2020-03-01' | today > '2023-02-28'))
```
```{r}
# 3. GPS accuracy exclusion (>5 meters)

data_3 <- data_2 %>%
  filter(X_Take.a.GPS.point_precision<=5)


```



```{r}
# 4. Filter NAs for snail reports - will filter any row that has at least one NA
#In my data there are no NAs for any of the snail reports so I didn't refine this filter
data_4 <- data_3 %>%
  filter(
    !is.na(What.is.the.number.of.Biomphalaria.specimens...example.shown.below.),
    !is.na(What.is.the.number.of.Bulinus.specimens...example.shown.below.),
    !is.na(What.is.the.number.of.Lymnaea.specimens...example.shown.below.)
  )

# error checks
#print(sum(data_4$Bio_Error, na.rm = TRUE))
#print(sum(data_4$Bul_Error, na.rm = TRUE))
#print(sum(data_4$Lym_Error, na.rm = TRUE))

```

```{r}

#4. Flag the rows invalid for each species

#Lym check 
#Rationale: If there is a lym error but no other snails that exist including pool, this means the CS photo was invalid and had no identifiable snails. I assign value to new field Lym_invalid = 1.

#I
data_4_lym <- data_3 %>%
  mutate(Lym_invalid = ifelse(
    Lym_Error == 1 & 
    is.na(Lym_Error_bio_exist) & 
    is.na(Lym_Error_bul_exist) & 
    is.na(Lym_Error_pool_exist) & 
    is.na(lym_Error_lym_exist), 
    1, 0  # Assign 1 if condition is met, otherwise 0
  ))

data_4_lym %>%
  group_by(Lym_Error, Lym_Error_bio_exist, Lym_Error_bul_exist, Lym_Error_pool_exist, lym_Error_lym_exist) %>%
  summarise(count = n(), .groups = "drop")

#sum(data_4_lym$Lym_invalid == 1, na.rm = TRUE)


#Breakdown of errors
#Lym_Error = 0: 3,300 rows
#Lym_Error = 1 AND Lym_Error_pool_exist = 1: 2,896
#Lym_Error = 1 AND all cases NA: 208 (invalid reports)
#Lym_Error = 1 AND Lym_Error_pool_exist = 1 AND Lym_Error_Lym_Exist = 1: 140
#Lym_Error = 1 AND Lym_Error_Lym_Exist = 1: 19
#Lym_Error = 1 and combination of other cases: 15

```

```{r}
#Bio check

data_4_lym_bio <- data_4_lym %>%
  mutate(Bio_invalid = ifelse(
    Bio_Error == 1 & 
    is.na(Bio_Error_bio_exist) & 
    is.na(Bio_Error_bul_exist) & 
    is.na(Bio_Error_pool_exist) & 
    is.na(Bio_Error_lym_exist), 
    1, 0  # Assign 1 if condition is met, otherwise 0
  ))

data_4_lym_bio %>%
  group_by(Bio_Error, Bio_Error_bio_exist, Bio_Error_bul_exist, Bio_Error_pool_exist, Bio_Error_lym_exist) %>%
  summarise(count = n(), .groups = "drop")

#sum(data_4_lym_bio$Bio_invalid == 1, na.rm = TRUE)

#Breakdown of errors
#Bio_Error = 0: 5,984 rows
#Bio_Error = 1 AND Bio_Error_pool_exist = 1: 257
#Bio_Error = 1 AND all cases NA: 199 (invalid reports)
#Bio_Error = 1 AND Bio_Error_lym_exist = 1: 80
#Bio_Error = 1 AND Bio_Error_bio_Exist = 1: 37
#Bio_Error = 1 and other cases: 20

```
```{r}
#Bul check

data_4_lym_bio_bul <- data_4_lym_bio %>%
  mutate(Bul_invalid = ifelse(
    Bul_Error == 1 & 
    is.na(Bul_Error_bio_exist) & 
    is.na(Bul_Error_bul_exist) & 
    is.na(Bul_Error_pool_exist) & 
    is.na(Bul_Error_lym_exist), 
    1, 0  # Assign 1 if condition is met, otherwise 0
  ))

data_4_lym_bio_bul %>%
  group_by(Bul_Error, Bul_Error_bio_exist, Bul_Error_bul_exist, Bul_Error_pool_exist, Bul_Error_lym_exist) %>%
  summarise(count = n(), .groups = "drop")

#sum(data_4_lym_bio_bul$Bul_invalid == 1, na.rm = TRUE)

#Breakdown of errors
#Bul_Error = 0: 5,700 rows
#Bul_Error = 1 AND Bul_Error_lym_exist = 1: 580
#Bio_Error = 1 AND Bul_error_pool_exist = 1: 154
#Bul_Error = 1 AND all cases NA: 105 (invalid reports)
#Bul_Error = 1 and other cases: 38
```

```{r}
#5. Filter out all rows where Lym_invalid = Bio_invalid = Bul_invalid = 1

data_5 <- data_4_lym_bio_bul %>%
  filter(!(Lym_invalid == 1 & Bio_invalid == 1 & Bul_invalid == 1))

#27 rows are completely invalid
#When generating occurrence sheet, we will filter whether to report the taxon presence/absence based on this field
```

```{r}
#6 - Add expert-validated count column to compile expert validated count data

data_6 <- data_5 %>%
  mutate(
    Bio_expert_count = ifelse(Bio_Error == 1, ifelse(is.na(bio_count), 0, bio_count), 
                              What.is.the.number.of.Biomphalaria.specimens...example.shown.below.),
    
    Bul_expert_count = ifelse(Bul_Error == 1, ifelse(is.na(bul_count), 0, bul_count), 
                              What.is.the.number.of.Bulinus.specimens...example.shown.below.),
    
    Lym_expert_count = ifelse(Lym_Error == 1, ifelse(is.na(lym_count), 0, lym_count), 
                              What.is.the.number.of.Lymnaea.specimens...example.shown.below.)
  )

```
```{r}

# 7. Add expert-validated occurrence columns based on count

data_7 <- data_6 %>%
  mutate(
    bio_occurrence = ifelse(Bio_expert_count == 0, 0, 1),
    bul_occurrence = ifelse(Bul_expert_count == 0, 0, 1),
    lym_occurrence = ifelse(Lym_expert_count == 0, 0, 1)
  )

#write.csv(data_7, "snail_occurrences_check.csv", row.names = FALSE)
```
```{r}
# 8 - Calculate sampling time

# Extract the start and end hours from the relevant columns
start_hour <- sub("^(\\d{2}:\\d{2}).*", "\\1", data_7$What.is.the.time.now.)
final_hour <- sub("^(\\d{2}:\\d{2}).*", "\\1", data_6$You.are.done.scooping..What.is.the.time.now.)

# Convert time strings to minutes
time_to_minutes <- function(time_str) {
  hm <- strsplit(time_str, ":")[[1]]
  return(as.integer(hm[1]) * 60 + as.integer(hm[2]))  # Convert to minutes
}

# Convert the time columns to minutes
minutes_vector1 <- sapply(final_hour, time_to_minutes)
minutes_vector2 <- sapply(start_hour, time_to_minutes)

# Calculate the sampling time in minutes
data_7$Sampling_time <- minutes_vector1 - minutes_vector2

# Count the number of NAs in Sampling_time column
na_count <- sum(is.na(data_7$Sampling_time))

# Print the count of NAs: 1,319 (due to missing start or finish time)
print(paste("Number of NA values in Sampling_time: ", na_count))

# View the updated data frame
#head(data_7)
```
```{r}
data_8 <- data_7 %>%
  filter(!(Sampling_time < 1 | Sampling_time > 60)) 
  
#write.csv(data_8, "updated_snail_data_with_samplingtime.csv", row.names = FALSE)
#1 minute or more: 4954 rows
#1 - 60 minutes: 4921 rows
#15 - 60 mins: 4080 rows
#20 - 60 mins: 3751 rows

#1 - 90 minutes: 4940
#15 - 90 minutes: 4099
#20 - 90 minutes: 3770


```
```{r}

# 9 - Format date to ISO 8601

library(lubridate)

# Combine date and time columns
data_8$eventDate <- paste(data_8$today, data_8$Enter.the.starting.time)

data_8$eventDate <- as.POSIXct(data_8$eventDate, format="%Y-%m-%d %H:%M", tz="UTC")

# Format the date as ISO 8601
data_8$eventDate <- format(data_8$eventDate, "%Y-%m-%dT%H:%M:%S")

data_9 <- data_8

```
```{r}
# Initialize new columns with GBIF standardized names

data_10 <- data_9 %>%
  mutate(
    parentEventID = "ATRAP1-CD",
    eventID = X_id,  # Copy values from _id
    samplingProtocol = "Brees et al. (2021). The Potential of Citizen-Driven Monitoring of Freshwater Snails in Schistosomiasis Research. https://doi.org/10.5334/cstp.388",  # Populate all rows with Brees protocol
    sampleSizeValue = paste(Sampling_time),
    sampleSizeUnit = paste("minutes"),
    samplingEffort = paste(Sampling_time, "minutes"),  # Copy values from Sampling_time and add "minutes"
    decimalLatitude = X_Take.a.GPS.point_latitude,  # Copy values from _Take a GPS point_latitude
    decimalLongitude = X_Take.a.GPS.point_longitude,  # Copy values from _Take a GPS point_longitude
    geodeticDatum = "WGS84",  # Populate all rows with "WGS84"
    countryCode = "CD",  # Populate all rows with "CD" for DR Congo
    coordinateUncertaintyInMeters = paste(X_Take.a.GPS.point_precision), #GPS accuracy
    institutionCode = "RMCA"
  )

```

```{r}
#10. Create the SAMPLING EVENT sheet for the dataset (1/2)

# Specify the columns you want to include in the new CSV file
GBIF_columns <- c("parentEventID", "eventID", "eventDate", "samplingProtocol", 
                        "sampleSizeValue", "sampleSizeUnit", 
                        "samplingEffort", "decimalLatitude", 
                        "decimalLongitude", "coordinateUncertaintyInMeters", 
                        "geodeticDatum", "countryCode", "institutionCode")

# Create a new data frame with the selected columns
Sampling_Event_Table <- data_10[ , GBIF_columns]

# Write the data frame to a CSV file
write.csv(Sampling_Event_Table, "Sampling_Event_Table_20250104_CD_v2.csv", row.names = FALSE)

```
```{r}
#10.5 create the recordedBy field, as recommended, to credit CS and validator

# Read the CS_ID_name.csv file
CS_ID_data <- read.csv("CS_ID_name_mod.csv", sep = ",", header = TRUE)

# Convert both columns to character before joining
data_10 <- data_10 %>%
  mutate(ID_mod = as.character(ID_mod))

CS_ID_data <- CS_ID_data %>%
  mutate(CS_ID = as.character(CS_ID))

CS_ID_data <- CS_ID_data %>%
  distinct(CS_ID, .keep_all = TRUE)

# Merge data and modify recordedBy column
data_10a <- data_10 %>%
  left_join(CS_ID_data, by = c("ID_mod" = "CS_ID")) %>%
  rename(recordedBy = CS_code) %>%
  mutate(recordedBy = ifelse(!is.na(recordedBy), paste0(recordedBy), "Unknown")) 

```

```{r}
# Define species categories
species_info <- data.frame(
  species_code = c("-01", "-02", "-03"),
  scientificName = c("Biomphalaria", "Bulinus", "Radix")
)
```

```{r}
# Expand data_10 three times (once for each species) and apply the error handling logic
data_11 <- data_10a %>%
  slice(rep(1:n(), each = 3)) %>%  # Repeat each row 3 times
  group_by(eventID) %>%  # Group to ensure indexing aligns properly
  mutate(
    species_index = rep(1:3, length.out = n()),  # Assign species index (1-3)
    occurrenceID = paste0(eventID, species_info$species_code[species_index]),
    scientificName = species_info$scientificName[species_index],
    individualCount = case_when(
      species_index == 1 & Bio_invalid != 1 ~ Bio_expert_count,  # Only include if Bio_invalid != 1
      species_index == 2 & Bul_invalid != 1 ~ Bul_expert_count,  # Only include if Bul_invalid != 1
      species_index == 3 & Lym_invalid != 1 ~ Lym_expert_count,  # Only include if Lym_invalid != 1
      TRUE ~ NA_real_  # Otherwise, set individualCount to NA
    ),
    # Logic for MachineObservation_bio
    #only provide the image where the taxon is sure to exist
    MachineObservation_bio = case_when(
      species_index == 1 & bio_occurrence == 1 & Bio_Error == 0 ~ `Place.all.Biomphalaria.specimens.on.the.scale.paper.and.take.a.photograph.`,
      species_index == 1 & bio_occurrence == 1 & Bio_Error == 1 & Bio_Error_bio_exist == 1 ~ `Place.all.Biomphalaria.specimens.on.the.scale.paper.and.take.a.photograph.`,
      species_index == 1 & bio_occurrence == 1 & Bio_Error == 1 & (is.na(Bio_Error_bio_exist) | Bio_Error_bio_exist == 0) & Lym_Error_bio_exist == 1 ~ `Place.all.Lymnaea.specimens.on.the.scale.paper.and.take.a.photograph.`,
      species_index == 1 & bio_occurrence == 1 & Bio_Error == 1 & (is.na(Bio_Error_bio_exist) | Bio_Error_bio_exist == 0) & Bul_Error_bio_exist == 1 ~ `Place.all.Bulinus.specimens.on.the.scale.paper.and.take.a.photograph.`,
      TRUE ~ NA_character_
    ),

    # Logic for MachineObservation_bul
    MachineObservation_bul = case_when(
      species_index == 2 & bul_occurrence == 1 & Bul_Error == 0 ~ `Place.all.Bulinus.specimens.on.the.scale.paper.and.take.a.photograph.`,
      species_index == 2 & bul_occurrence == 1 & Bul_Error == 1 & Bul_Error_bul_exist == 1 ~ `Place.all.Bulinus.specimens.on.the.scale.paper.and.take.a.photograph.`,
      species_index == 2 & bul_occurrence == 1 & Bul_Error == 1 & (is.na(Bul_Error_bul_exist) | Bul_Error_bul_exist == 0) & Bio_Error_bul_exist == 1 ~ `Place.all.Biomphalaria.specimens.on.the.scale.paper.and.take.a.photograph.`,
      species_index == 2 & bul_occurrence == 1 & Bul_Error == 1 & (is.na(Bul_Error_bul_exist) | Bul_Error_bul_exist == 0) & Lym_Error_bul_exist == 1 ~ `Place.all.Lymnaea.specimens.on.the.scale.paper.and.take.a.photograph.`,
      TRUE ~ NA_character_
    ),

    # Logic for MachineObservation_rad
    MachineObservation_rad = case_when(
      species_index == 3 & lym_occurrence == 1 & Lym_Error == 0 ~ `Place.all.Lymnaea.specimens.on.the.scale.paper.and.take.a.photograph.`,
      species_index == 3 & lym_occurrence == 1 & Lym_Error == 1 & lym_Error_lym_exist == 1 ~ `Place.all.Lymnaea.specimens.on.the.scale.paper.and.take.a.photograph.`,
      species_index == 3 & lym_occurrence == 1 & Lym_Error == 1 & (is.na(lym_Error_lym_exist) | lym_Error_lym_exist == 0) & Bio_Error_lym_exist == 1 ~ `Place.all.Biomphalaria.specimens.on.the.scale.paper.and.take.a.photograph.`,
      species_index == 3 & lym_occurrence == 1 & Lym_Error == 1 & (is.na(lym_Error_lym_exist) | lym_Error_lym_exist == 0) & Bul_Error_lym_exist == 1 ~ `Place.all.Bulinus.specimens.on.the.scale.paper.and.take.a.photograph.`,
      TRUE ~ NA_character_
    ),

    # Assign MachineObservation to the corresponding species
    MachineObservation = case_when(
      species_index == 1 ~ MachineObservation_bio,
      species_index == 2 ~ MachineObservation_bul,
      species_index == 3 ~ MachineObservation_rad,
      TRUE ~ NA_character_
    ),
   occurrenceStatus = case_when(
      individualCount > 0 ~ "present",
      individualCount == 0 ~ "absent",
      TRUE ~ NA_character_  # If individualCount is NA, the status is also NA
      ),
    organismQuantity = individualCount,
    organismQuantityType = "individuals",
    basisOfRecord = "LivingSpecimen"
  ) %>%
  ungroup()  %>%
  filter(!is.na(individualCount)) %>% # Remove rows where individualCount is NA (i.e., skipped species)
  select(eventID, occurrenceID,
         individualCount, organismQuantity, organismQuantityType, basisOfRecord,
         occurrenceStatus, scientificName, recordedBy, MachineObservation)

```



```{r}
# Expand data_10 three times (once for each species) and apply the invalid check
data_11 <- data_10a %>%
  slice(rep(1:n(), each = 3)) %>%  
  group_by(eventID) %>% 
  mutate(
    species_index = rep(1:3, length.out = n()),  # Assign species index (1-3)
    occurrenceID = paste0(eventID, species_info$species_code[species_index]),
    scientificName = species_info$scientificName[species_index],
    
    # MachineObservation_bio, _bul, _rad created conditionally based on occurrences
    MachineObservation_bio = case_when(
      species_index == 1 & bio_occurrence == 1 ~ `Place.all.Biomphalaria.specimens.on.the.scale.paper.and.take.a.photograph.`,
      TRUE ~ NA_character_  # Leave blank if species_index is not 1 or bio_occurrence != 1
    ),
    
    MachineObservation_bul = case_when(
      species_index == 2 & bul_occurrence == 1 ~ `Place.all.Bulinus.specimens.on.the.scale.paper.and.take.a.photograph.`,
      TRUE ~ NA_character_  # Leave blank if species_index is not 2 or bul_occurrence != 1
    ),
    
    MachineObservation_rad = case_when(
      species_index == 3 & lym_occurrence == 1 ~ `Place.all.Lymnaea.specimens.on.the.scale.paper.and.take.a.photograph.`,
      TRUE ~ NA_character_  # Leave blank if species_index is not 3 or lym_occurrence != 1
    ),
    # Create a single 'MachineObservation' column that combines the three specific species observations
    MachineObservation = case_when(
      species_index == 1 ~ MachineObservation_bio,
      species_index == 2 ~ MachineObservation_bul,
      species_index == 3 ~ MachineObservation_rad,
      TRUE ~ NA_character_  # Leave blank if none of the conditions match
    ),
    organismQuantityType = "individuals",
    basisOfRecord = "LivingSpecimen"
  ) %>%
  ungroup() %>%
  filter(!is.na(MachineObservation_bio) | !is.na(MachineObservation_bul) | !is.na(MachineObservation_rad))  # Remove rows where all MachineObservation columns are NA
```


```{r}
# Save the resulting data to a CSV
write.csv(data_11, "NEW_output_data.csv", row.names = FALSE)
```

```{r}
# Define paths
source_folder <- 'KOBO_Congo'
destination_folder <- 'Kobo_Congo_clean_test'
```

```{r}
# Assuming your dataframe is named df and has a column "MachineObservation"
image_names <- na.omit(data_11$MachineObservation)  # Remove NA
image_names <- image_names[image_names != ""]  # Remove empty strings

image_names <- sub("-original$", "", image_names)

image_folders <- data_11$X_uuid  # Folder names are listed in X_uuid


```

```{r}
# Full source paths by combining source folder, X_uuid partition, and image names
source_paths <- file.path(source_folder, image_folders, image_names)

#cat("First few constructed paths:\n")
print(head(source_paths))
```
```{r}
 #Check if all the image files exist
#missing_files <- source_paths[!file.exists(source_paths)]

# Count the number of missing files
#missing_file_count <- length(missing_files)

# Count the number of non-missing files
#non_missing_file_count <- length(source_paths) - missing_file_count
```


```{r}
# Print results
if (missing_file_count > 0) {
  cat("Missing files:\n", paste(missing_files, collapse = "\n"))
} else {
  cat("All files found!\n")
}

cat("Number of missing files:", missing_file_count, "\n \n")
cat("Number of non-missing files:", non_missing_file_count, "\n")
```
```{r}
# Create full source paths
source_paths <- file.path(source_folder, image_folders, image_names)

# Create full destination paths
destination_paths <- file.path(destination_folder, image_names)

# Copy files
copy_results <- file.copy(source_paths, destination_paths, overwrite = TRUE)

# Check for missing files
missing_files <- image_names[!file.exists(source_paths)]

# Print missing files
if (length(missing_files) > 0) {
  cat("Missing files:\n", paste(missing_files, collapse = "\n"))
} else {
  cat("All files copied successfully!")
}
```
```{r}
#10. Create the SAMPLING EVENT sheet for the dataset (1/2)

# Specify the columns you want to include in the new CSV file
GBIF_columns <- c("parentEventID", "eventID", "eventDate", "samplingProtocol", 
                        "sampleSizeValue", "sampleSizeUnit", 
                        "samplingEffort", "decimalLatitude", 
                        "decimalLongitude", "coordinateUncertaintyInMeters", 
                        "geodeticDatum", "countryCode", "institutionCode")

# Create a new data frame with the selected columns
Sampling_Event_Table <- data_10[ , GBIF_columns]

# Write the data frame to a CSV file
write.csv(Sampling_Event_Table, "Sampling_Event_Table_20250104_CD.csv", row.names = FALSE)

```
```{r}
#12. Add new (optional) GBIF fields + identifiedBy field

data_12 <- data_11 %>%
  mutate(
    identifiedBy = "Larissa Bonifacio",
    Kingdom = "Animalia",
    Phylum = "Mollusca",
    Class = "Gastropoda",
    Order = "Hygrophila",
    Family = ifelse(scientificName == "Radix", "Lymnaeidae", "Planorbidae"),
    TaxonRank = "genus"
  )
```
```{r}
write.csv(data_12, "Associated_Occurrences_Table_20250104_CD.csv", row.names = FALSE)

```

